<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    public function run()
    {
        // Fetch state_id dynamically by name
        $stateIds = DB::table('states')->pluck('id', 'name');

        // Example: ['Maharashtra' => 5, 'Karnataka' => 6, ...]

        

        $districts = [
            ['country_id' => 1,'name' => 'Anantapur', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Chittoor', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Cuddapah', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'East Godavari', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Guntur', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Krishna', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Kurnool', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Mahaboob Nagar', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Nellore', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Prakasam', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Srikakulam', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Visakhapatnam', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Vizianagaram', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'West Godavari', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Y.S.R.', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Tirupati', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Annamayya', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Parvathipuramu Manyam', 'state' => 'AndhraPradesh'],
            ['country_id' => 1,'name' => 'Baksa', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Barpeta', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Bongaigaon', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Cachar', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Chirang', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Darrang', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Dhemaji', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Dhubri', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Dibrugarh', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Dima Hasao', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Goalpara', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Golaghat', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Hailakandi', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Jorhat', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Kamrup', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Kamrup Metropolitan', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Karbi Anglong', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Karimganj', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Kokrajhar', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Lakhimpur', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Morigaon', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Nagaon', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Nalbari', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Sivasagar', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Sonitpur', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Tinsukia', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Udalguri', 'state' => 'Assam'],
            ['country_id' => 1,'name' => 'Bemetara ', 'state' => 'Assam '],
            ['country_id' => 1,'name' => 'Charaideo', 'state' => 'Assam '],
            ['country_id' => 1,'name' => 'West Karbi Anglong ', 'state' => 'Assam '],
            ['country_id' => 1,'name' => 'Hojai', 'state' => 'Assam '],
            ['country_id' => 1,'name' => 'Araria', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Arwal', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Aurangabad', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Banka', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Begusarai', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Bhagalpur', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Bhojpur', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Buxar', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Darbhanga', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Gaya', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Gopalganj', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Jamui', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Jehanabad', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Kaimur (Bhabua)', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Katihar', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Khagaria', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Kishanganj', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Lakhisarai', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Madhepura', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Madhubani', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Munger', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Muzaffarpur', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Nalanda', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Nawada', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Pashchim Champaran', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Patna', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Purba Champaran', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Purnia', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Rohtas', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Saharsa', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Samastipur', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Saran', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Sheikhpura', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Sheohar', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Sitamarhi', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Siwan', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Supaul', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Vaishali', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'East Champaran', 'state' => 'Bihar'],
            ['country_id' => 1,'name' => 'Bastar', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Bijapur', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Bilaspur', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Dakshin Bastar Dantewada', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Dhamtari', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Durg', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Janjgir - Champa', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Jashpur', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Kabeerdham', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Korba', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Koriya', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Mahasamund', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Narayanpur', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Raigarh', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Raipur', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Rajnandgaon', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Surguja', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Uttar Bastar Kanker', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Dantewada', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Gariyaband', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Mungeli ', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Sukma', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'Surajpur', 'state' => 'Chattisgarh'],
            ['country_id' => 1,'name' => 'South Goa', 'state' => 'Goa'],
            ['country_id' => 1,'name' => 'North Goa', 'state' => 'Goa'],
            ['country_id' => 1,'name' => 'Rajkot', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Ahmedabad', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Vadodara', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Anand', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Chhota Udaipur', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Dahod', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Kheda', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Mahisagar', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Panchmahal', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Gandhinagar', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Aravalli', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Banaskantha', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Mehsana', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Patan', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Sabarkantha', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Kutch', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Amreli', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Bhavnagar', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Botad', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Devbhoomi Dwarka', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Jamnagar', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Junagadh', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Morbi', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Porbandar', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Surendranagar', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Surat', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Bharuch', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Dang', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Narmada', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Navsari', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Tapi', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Valsad', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Vav-Tharad', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Gir Somnath', 'state' => 'Gujarat'],
            ['country_id' => 1,'name' => 'Ambala', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Bhiwani', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Faridabad', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Fatehabad', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Gurgaon', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Hisar', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Jhajjar', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Jind', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Kaithal', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Karnal', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Kurukshetra', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Mahendragarh', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Mewat', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Palwal', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Panchkula', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Panipat', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Rewari', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Rohtak', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Sirsa', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Sonipat', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Yamunanagar', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Charkhi Dadri ', 'state' => 'Haryana'],
            ['country_id' => 1,'name' => 'Bilaspur', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Chamba', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Hamirpur', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Kangra', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Kinnaur', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Kullu', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Lahul & Spiti', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Mandi', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Shimla', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Sirmaur', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Solan', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Una', 'state' => 'HimachalPradesh'],
            ['country_id' => 1,'name' => 'Bokaro', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Chatra', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Deoghar', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Dhanbad', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Dumka', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Garhwa', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Giridih', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Godda', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Gumla', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Hazaribagh', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Jamtara', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Khunti', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Kodarma', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Latehar', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Lohardaga', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Pakur', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Palamu', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Pashchimi Singhbhum', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Purbi Singhbhum', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Ramgarh', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Ranchi', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Sahibganj', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Saraikela-Kharsawan', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Simdega', 'state' => 'Jharkhand'],
            ['country_id' => 1,'name' => 'Bagalkot', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Bangalore', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Bangalore Rural', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Belgaum', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Bellary', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Bidar', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Bijapur', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Chamarajanagar', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Chikkaballapura', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Chikmagalur', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Chitradurga', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Dakshina Kannada', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Davanagere', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Dharwad', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Gadag', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Gulbarga', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Hassan', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Haveri', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Kodagu', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Kolar', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Koppal', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Mandya', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Mysore', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Raichur', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Ramanagara', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Shimoga', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Tumkur', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Udupi', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Uttara Kannada', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Yadgir', 'state' => 'Karnataka'],
            ['country_id' => 1,'name' => 'Alappuzha', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Ernakulam', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Idukki', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Kannur', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Kasaragod', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Kollam', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Kottayam', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Kozhikode', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Malappuram', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Palakkad', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Pathanamthitta', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Thiruvananthapuram', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Thrissur', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Wayanad', 'state' => 'Kerala'],
            ['country_id' => 1,'name' => 'Alirajpur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Anuppur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Ashoknagar', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Balaghat', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Barwani', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Betul', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Bhind', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Bhopal', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Burhanpur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Chhatarpur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Chhindwara', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Damoh', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Datia', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Dewas', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Dhar', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Dindori', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Khandwa', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Guna', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Gwalior', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Harda', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Narmadapuram', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Indore', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Jabalpur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Jhabua', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Katni', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Mandla', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Mandsaur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Morena', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Narsimhapur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Neemuch', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Panna', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Raisen', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Rajgarh', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Ratlam', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Rewa', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Sagar', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Satna', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Sehore', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Seoni', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Shahdol', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Agar Malwa', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Shajapur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Sheopur', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Shivpuri', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Sidhi', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Singrauli', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Tikamgarh', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Ujjain', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Umaria', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Vidisha', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Khargone', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Pandhurna', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Mauganj', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Maihar', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Niwari', 'state' => 'MadhyaPradesh'],
            ['country_id' => 1,'name' => 'Ahmadnagar', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Akola', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Amravati', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Aurangabad', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Bhandara', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Beed', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Buldana', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Chandrapur', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Dhule', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Gadchiroli', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Gondiya', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Hingoli', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Jalgaon', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Jalna', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Kolhapur', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Latur', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Nagpur', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Nanded', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Nandurbar', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Nashik', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Osmanabad', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Parbhani', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Pune', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Raigarh', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Ratnagiri', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Sangli', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Satara', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Sindhudurg', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Solapur', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Thane', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Wardha', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Washim', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Yavatmal', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Mumbai', 'state' => 'Maharashtra'],
            ['country_id' => 1,'name' => 'Bishnupur', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Chandel', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Churachandpur', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Imphal East', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Imphal West', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Senapati', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Tamenglong', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Thoubal', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'Ukhrul', 'state' => 'Manipur'],
            ['country_id' => 1,'name' => 'East Garo Hills', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'East Khasi Hills', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'Jaintia Hills', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'Ribhoi', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'South Garo Hills', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'West Garo Hills', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'West Khasi Hills', 'state' => 'Meghalaya'],
            ['country_id' => 1,'name' => 'Aizawl', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Champhai', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Kolasib', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Lawngtlai', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Lunglei', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Mamit', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Saiha', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Serchhip', 'state' => 'Mizoram'],
            ['country_id' => 1,'name' => 'Dimapur', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Kiphire', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Kohima', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Longleng', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Mokokchung', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Mon', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Peren', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Phek', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Tuensang', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Wokha', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Zunheboto', 'state' => 'Nagaland'],
            ['country_id' => 1,'name' => 'Karaikal', 'state' => 'Puducherry'],
            ['country_id' => 1,'name' => 'Mahe', 'state' => 'Puducherry'],
            ['country_id' => 1,'name' => 'Puducherry', 'state' => 'Puducherry'],
            ['country_id' => 1,'name' => 'Yanam', 'state' => 'Puducherry'],
            ['country_id' => 1,'name' => 'Amritsar', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Barnala', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Bathinda', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Faridkot', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Fatehgarh Sahib', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Firozpur', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Gurdaspur', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Hoshiarpur', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Jalandhar', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Kapurthala', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Ludhiana', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Mansa', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Moga', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Muktsar', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Patiala', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Rupnagar', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Sahibzada Ajit Singh Nagar', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Sangrur', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Shahid Bhagat Singh Nagar', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Tarn Taran', 'state' => 'Punjab'],
            ['country_id' => 1,'name' => 'Ajmer', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Alwar', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Banswara', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Baran', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Barmer', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Bharatpur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Bhilwara', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Bikaner', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Bundi', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Chittaurgarh', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Churu', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Dausa', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Dhaulpur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Dungarpur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Ganganagar', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Hanumangarh', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Jaipur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Jaisalmer', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Jalor', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Jhalawar', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Jhunjhunun', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Jodhpur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Karauli', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Kota', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Nagaur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Pali', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Pratapgarh', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Rajsamand', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Sawai Madhopur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Sikar', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Sirohi', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Tonk', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'Udaipur', 'state' => 'Rajasthan'],
            ['country_id' => 1,'name' => 'East District', 'state' => 'Sikkim'],
            ['country_id' => 1,'name' => 'North District', 'state' => 'Sikkim'],
            ['country_id' => 1,'name' => 'South District', 'state' => 'Sikkim'],
            ['country_id' => 1,'name' => 'West District', 'state' => 'Sikkim'],
            ['country_id' => 1,'name' => 'Ariyalur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Coimbatore', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Cuddalore', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Dharmapuri', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Dindigul', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Erode', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Kancheepuram', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Kanniyakumari', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Karur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Krishnagiri', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Madurai', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Nagapattinam', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Namakkal', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Perambalur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Pudukkottai', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Ramanathapuram', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Salem', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Sivaganga', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Thanjavur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'The Nilgiris', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Theni', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Thiruvallur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Thiruvarur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Thoothukkudi', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Tiruchirappalli', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Tirunelveli', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Tiruppur', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Tiruvannamalai', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Vellore', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Viluppuram', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Virudhunagar', 'state' => 'TamilNadu'],
            ['country_id' => 1,'name' => 'Adilabad', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Bhadradri Kothagudem ', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Bhadradri Kothagudem', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Hyderabad', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Jagitial', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Jangaon', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Jayashankar Bhupalpally', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Jogulamba Gadwal', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Kamareddy', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Karimnagar', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Khammam', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Mahbubnagar', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Medak', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Medchal–Malkajgiri', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Mulugu', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Nalgonda', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Nizamabad', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Ranga Reddy', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Sangareddy', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Siddipet', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Suryapet', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Vikarabad', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Wanaparthy', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Warangal', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Yadadri Bhuvanagiri', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Hanumakonda', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Kumuram Bheem', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Mahabubabad', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Mancherial', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Nagarkurnool', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Narayanpet', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Nirmal', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Peddapalli', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Rajanna Sircilla', 'state' => 'Telangana'],
            ['country_id' => 1,'name' => 'Dhalai', 'state' => 'Tripura'],
            ['country_id' => 1,'name' => 'North Tripura', 'state' => 'Tripura'],
            ['country_id' => 1,'name' => 'South Tripura', 'state' => 'Tripura'],
            ['country_id' => 1,'name' => 'West Tripura', 'state' => 'Tripura'],
            ['country_id' => 1,'name' => 'Almora', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Bageshwar', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Chamoli', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Champawat', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Dehradun', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Garhwal', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Hardwar', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Nainital', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Pithoragarh', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Rudraprayag', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Tehri Garhwal', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Udham Singh Nagar', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Uttarkashi', 'state' => 'Uttarakhand'],
            ['country_id' => 1,'name' => 'Agra', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Aligarh', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Allahabad', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Ambedkar Nagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Auraiya', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Azamgarh', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Baghpat', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bahraich', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Ballia', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Balrampur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Banda', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bara Banki', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bareilly', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Basti', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bijnor', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Budaun', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bulandshahr', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Chandauli', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Chitrakoot', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Deoria', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Etah', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Etawah', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Ayodhya', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Farrukhabad', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Fatehpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Firozabad', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Gautam Buddha Nagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Ghaziabad', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Ghazipur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Gonda', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Gorakhpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Hamirpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Hardoi', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Jalaun', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Jaunpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Jhansi', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Jyotiba Phule Nagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kannauj', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kanpur Dehat', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kanpur Nagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kasganj', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kaushambi', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kheri', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Hathras', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Amethi', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Amroha', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Hapur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Kushinagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Lakhimpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Lalitpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Lucknow', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Maharajganj', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Mahoba', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Mainpuri', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Mathura', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Mau', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Meerut', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Mirzapur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Moradabad', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Muzaffarnagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Pilibhit', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Pratapgarh', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Prayagraj', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Raebareli', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Rampur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Saharanpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Sant Kabir Naga', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bhadohi', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Sambhal', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Shahjahanpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Shamli', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Shravasti', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Siddharthnagar', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Sitapur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Sonbhadra', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Sultanpur', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Unnao', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Varanasi', 'state' => 'UttarPradesh'],
            ['country_id' => 1,'name' => 'Bankura', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Barddhaman', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Birbhum', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Dakshin Dinajpur', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Darjiling', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Howrah', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Hooghly', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Jalpaiguri', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Cooch Behar', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Maldah', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Murshidabad', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Nadia', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'North 24 Parganas', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Paschim Medinipur', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Purba Medinipur', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Puruliya', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'South 24 Parganas', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Uttar Dinajpur', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Alipurduar', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Jhargram', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Kolkata', 'state' => 'WestBengal'],
            ['country_id' => 1,'name' => 'Kalimpong', 'state' => 'WestBengal'],
        ];

        foreach ($districts as $district) {
            $stateId = $stateIds[$district['state']] ?? null;

            if ($stateId) {
                DB::table('districts')->updateOrInsert(
                    ['country_id' => $district['country_id'],'name' => $district['name'], 'state_id' => $stateId],
                    ['state_id' => $stateId]
                );
            }
        }
    }
}
